version: "3.9"

services:
  web:
    build: .
    command: ["gunicorn", "Weather.wsgi:application", "--bind", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
      SECRET_KEY: ${SECRET_KEY}
      PYTHONUNBUFFERED: 1
      DJANGO_SETTINGS_MODULE: Weather.settings
    depends_on:
      - db
    # Для разработки:
    volumes:
      - .:/app

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
