# Generated by Django 5.2.1 on 2025-05-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Город")),
                (
                    "searched_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата последнего поиска"
                    ),
                ),
                (
                    "session_key",
                    models.CharField(max_length=40, verbose_name="Сессионный ключ"),
                ),
            ],
        ),
    ]
